# Generated by Django 4.1.3 on 2023-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
    ]
