# Generated by Django 4.1.3 on 2023-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
    ]
